### ISSUE TITLE
Difficulty including HoaLibrary in standalone build

### ISSUE THREAD

**Issue by eflynch** [CICM/HoaLibrary-Max#1]
I'm trying to build a max patch as a standalone (mac os x) application which uses the hoa externals. For most externals the .mxo files get wrapped into the max collective file so they end up linking correctly when you start the standalone app. I am a bit baffled by where the objects in this library are actually defined in the package, but because they seem to be represented in some implicit way, they are not copied into the collective file. Please assist.

**Comment by eflynch** [comment]
Solved this one by copying the hoa.library.mxo file into the C74/extensions folder of the build. Apparentl Max doesn't copy in extensions from external packages when you make a standalone build automatically.

**Comment by eliottparis** [comment]
Hi, the new release (v2.2) should fix this.
Thanks.
