### ISSUE TITLE
hoa.3d.decoder~

### ISSUE THREAD

**Issue by martaolko** [CICM/HoaLibrary-Max#6]
Hello,
I am using HOALibrary in Max. I want to use the decoder with 20 speakers. How can I know which channel is going to which speaker? (in other words which channel is the 'back' etc.)
Thanks,
Marta

**Comment by pierreguillot** [comment]
Hi, 
It depends on the configuration. In 2d, if you use the decoder in regular mode, the angles are in increasing order (0° is the front). In irregular mode, you can you the attribute "@angles" with a liste of angles in degrees to specify the position of each channel. So if you have "@angles 0 180 90 270", you'll have the first channel at the front, the second behind, the third of the left and the fourth on the right. In 3d, the only mode is irregular so it has the same behavior but it uses a list of a pair of angles (the first one for the azimuth and the second one for the elevation). You should have a look at the tutorials and the help files for further information.
